apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-demo-app
  template:
    metadata:
      labels:
        app: gke-demo-app
    spec:
      containers:
      - name: gke-demo-app
        image: gcr.io/SEU_PROJETO/gke-demo-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gke-demo-app-service
spec:
  type: LoadBalancer
  selector:
    app: gke-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
